name: Star

on: [watch]

permissions: {}

jobs:
  star:
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@77eaa4f1c608a7d68b38af4e3f739dcd8cba273e # v3
        with:
          status: ${{ job.status }}
          fields: repo
          text: "<!channel> Star from ${{ github.event.sender.login }}, Total: ${{ github.event.repository.stargazers_count }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
